// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Inventory struct {
	ID       string `json:"ID"`
	Item     *Item  `json:"Item"`
	Location string `json:"Location"`
	Status   string `json:"Status"`
	Quantity int    `json:"Quantity"`
}

type Item struct {
	ID          string `json:"ID"`
	Sku         string `json:"SKU"`
	Description string `json:"Description"`
}

type NewInventory struct {
	ItemID   string `json:"ItemID"`
	Location string `json:"Location"`
	Status   string `json:"Status"`
	Quantity int    `json:"Quantity"`
}

type RemoveInventory struct {
	ItemID   string `json:"ItemID"`
	Location string `json:"Location"`
	Status   string `json:"Status"`
	Quantity int    `json:"Quantity"`
}
