name: build-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: webui/package-lock.json
    - name: npm ci
      working-directory: ./webui
      run: npm ci  
    - name: npm build
      working-directory: ./webui
      run: npm build

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...