name: Release testapp binaries

on:
  release:
    types: [created]

env:
  CMD_PATH: ./cmd/server

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: webui/package-lock.json
      - name: npm ci
        working-directory: ./webui
        run: npm ci  
      - name: Build Web UI
        working-directory: ./webui
        run: npm run build
      - name: Build
        run: go build -v ./...
      - name: Run tests
        run: go test -v ./...
      - uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.19
          compress_assets: false
          project_path: "${{ env.CMD_PATH }}"
          build_flags: -v
          binary_name: "testapp"
          ldflags: "-s -w"
          extra_files: LICENSE README.md